name: py_clarite
channels:
  - conda-forge
dependencies:
  - python<=3.9
  - jupyterlab
  - matplotlib
  - networkx
  - numpy
  - nxviz
  - pandas
  - pip
  - rpy2
  - scikit-learn
  - scipy
  - statsmodels
  - pip:
    - clarite

